class ProcuraTittlesAndLinks {
  static List<String> procuraTitle = [
    'Aula Paraná',
    'Canal do Professor',
    'Celem Curso de Idiomas',
    'Consulta Escolas',
    'Contracheque',
    'Credenciamento de Diretores',
    'Edutech Cursos de Programação',
    'E-Protocolo',
    'Expresso e-mail',
    'Fundepar',
    'GRHS Seed',
    'Histórico escolar',
    'Legislação',
    'Matrícula On-line',
    'Novo Ensino Médio',
    'Prova Paraná',
    'PSS',
    'Robótica Paraná',
    'Saúde do Servidor (SAS)',
    'Senhas',
    'Sistema RH Seed',
  ];
  static List<String> procuraLinks = [
    'https://www.aulaparana.pr.gov.br',
    'https://www.youtube.com/c/DiretoriadeEducaçãoSeedPR',
    'https://aluno.escoladigital.pr.gov.br/celem',
    'http://www.consultaescolas.pr.gov.br/consultaescolas-java/pages/templates/initial2.jsf;jsessionid=_NnoZlggbgJiZz1FTc_SI45pEXSbxqaOJowINRUX.sseed75003?windowId=915',
    'https://wwws.portaldoservidor.pr.gov.br/cchequenet/',
    'https://www.educacao.pr.gov.br/credenciamento_diretores',
    'https://www.educacao.pr.gov.br/programacao',
    'https://auth-cs.identidadedigital.pr.gov.br/centralautenticacao/login.html?response_type=code&client_id=9188905e74c28e489b44e954ec0b9bca&redirect_uri=https%3A%2F%2Fwww.eprotocolo.pr.gov.br%2Fspiweb&scope=null&state=1663949161905&urlCert=https://certauth-cs.identidadedigital.pr.gov.br&dnsCidadao=https://cidadao-cs.identidadedigital.pr.gov.br/centralcidadao&loginPadrao=btnCentral&labelCentral=CPF,Login%20Sentinela&modulosDeAutenticacao=btnSentinela,btnExpresso,btnCertificado,btnSms,btnCpf,btnEmailToken,btnSanepar,btnCentral&urlLogo=https%3A%2F%2Fwww.eprotocolo.pr.gov.br%2Fspiweb%2Fimages%2Flogo_eprotocolo.png&acesso=2072&tokenFormat=jwt&exibirLinkAutoCadastro=true&exibirLinkRecuperarSenha=true&exibirLinkAutoCadastroCertificado=false&captcha=false',
    'http://www.diaadiaeducacao.pr.gov.br/portals/frm_login.php?acesso=1&origem=email',
    'https://www.fundepar.pr.gov.br',
    'https://www.educacao.pr.gov.br/rh',
    'https://www.areadoaluno.seed.pr.gov.br/servicosaoaluno/pages/publico/login.jsf?dswid=3192',
    'https://www.educacao.pr.gov.br/Legislacao',
    'https://www.areadoaluno.seed.pr.gov.br/servicosaoaluno/pages/publico/login.jsf?dswid=3192',
    'https://professor.escoladigital.pr.gov.br/nem',
    'https://www.provaparana.pr.gov.br',
    'https://www.educacao.pr.gov.br/pss',
    'https://aluno.escoladigital.pr.gov.br/robotica',
    'http://www.administracao.pr.gov.br/SAS',
    'https://www.educacao.pr.gov.br/CAS',
    'https://auth-cs.identidadedigital.pr.gov.br/centralautenticacao/authenticationIdentidadeDigital.html?response_type=code&client_id=577bcc914f9e55d5e4e4f82f9f00e7d4&redirect_uri=http%3A%2F%2Fwww.rhseed.pr.gov.br&scope=central.cidadao.obterGruposSistema%20central.cidadao.solicitarAutoCadastro%20central.cidadao.consultar%20central.cidadao.desvincular.usuarios.grupo%20central.cidadao.vincular.usuarios.grupo%20centralcidadao.v1.cidadaos.cpf.get%20centralcidadao.v1.cidadaos.nome.get%20centralcidadao.v1.cidadaos.grupo.get%20centralcidadao.v1.grupos.cidadaos.put%20centralcidadao.v1.grupos.cidadaos.delete&state=1579094145570&urlCert=https://certauth-cs.identidadedigital.pr.gov.br&dnsCidadao=https://cidadao-cs.identidadedigital.pr.gov.br/centralcidadao&loginPadrao=btnCentral&labelCentral=E-Mail,Login%20Sentinela&modulosDeAutenticacao=btnSentinela,btnEmail,btnCentral&urlLogo=http://www.rhseed.pr.gov.br/rhseed/resources/images/logo-sistema-grande.png&acesso=2060',
  ];
}
